### ISSUE TITLE
returning 403 response

### ISSUE THREAD

**Issue by marcosh** [middlewares/recaptcha#1]
Returning a 403 response if the validation does not pass looks a reasonable default to me, but it is not always what a user may desire.

Maybe he wants to set a flash message and redirect to an error page, or who knows what else.

It would be nice to make this configurable, allowing the middleware to receive a callable returning an instance of `ResponseInterface`:

```php
class Recaptcha implements MiddlewareInterface
{
    public function __construct(callable $responseFactory = null)
    {
        if (null === $responseFactory) {
            $responseFactory = function () {return Utils\Factory::createResponse(403);}
        }
        $this->responseFactory = $responseFactory;
    }

    public function process(ServerRequestInterface $request, DelegateInterface $delegate)
    {
        if (!$this->isValid($request)) {
            return ($this->responseFactory)();
        }
    }
}
```

what do you say? Seems reasonable?

**Comment by oscarotero** [comment]
Hi.
To handle http errors, there's the [error-handler middleware](https://github.com/middlewares/error-handler), so you can do something like this:

```php
$handler = function ($request) {
    $error = $request->getAttribute('error');

    if ($error->getCode() === 403) {
        return 'You have not passed the recaptcha filter';
    }

    return 'Generic error';
};

$dispatcher = new Dispatcher([
    new Middlewares\ErrorHandler($handler),
    new Middlewares\Recaptcha($secretKey)
]);
```

**Comment by marcosh** [comment]
ah, ok! That's great! Thank you
